import { Provider, StateSummary, CategorySummary, CATEGORIES } from "./types";

// One sample listing per category, spread across different states, so the
// directory demonstrates full category coverage from day one. Real
// provider data replaces/extends this the moment Supabase is connected —
// see lib/data/providers.ts.

const IMG = {
  therapy: "https://images.unsplash.com/photo-1573497491208-6b1acb260507?w=1200&q=80",
  office: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&q=80",
  clinic: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=80",
  home: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
  senior: "https://images.unsplash.com/photo-1447069387593-a5de0862481e?w=1200&q=80",
  hands: "https://images.unsplash.com/photo-1584515933487-779824d29309?w=1200&q=80",
  garden: "https://images.unsplash.com/photo-1516307365426-bea591f05011?w=1200&q=80",
  nurse: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=1200&q=80",
};

export const providers: Provider[] = [
  {
    slug: "clearmind-therapy-partners",
    name: "Clearmind Therapy Partners",
    category: "Therapists",
    categorySlug: "therapists",
    state: "California",
    stateSlug: "california",
    address: "4200 Ocean Terrace Blvd",
    zip: "90045",
    phone: "(310) 555-0142",
    website: "https://example.com",
    description:
      "A group therapy practice offering individual and couples counseling for anxiety, depression, and life transitions, with evening and weekend availability.",
    servicesOffered: ["Individual Therapy", "Couples Counseling", "Telehealth Sessions", "Sliding Scale Intake"],
    insuranceAccepted: ["Private Insurance", "Self-Pay", "Sliding Scale"],
    hoursOfOperation: "Mon–Fri 8am–8pm, Sat 9am–2pm",
    contactFormEnabled: true,
    contactEmail: "hello@clearmindtherapy.example.com",
    socialLinks: { instagram: "https://instagram.com", linkedin: "https://linkedin.com" },
    verified: true,
    featured: true,
    claimed: true,
    isPremium: true,
    imageUrl: IMG.therapy,
    logoUrl: IMG.therapy,
    galleryUrls: [IMG.therapy, IMG.office],
  },
  {
    slug: "riverstone-psychological-associates",
    name: "Riverstone Psychological Associates",
    category: "Psychologists",
    categorySlug: "psychologists",
    state: "Texas",
    stateSlug: "texas",
    address: "118 Bay Vista Ave",
    zip: "78701",
    phone: "(512) 555-0198",
    website: "https://example.com",
    description:
      "Licensed clinical psychologists providing diagnostic testing, psychological evaluation, and evidence-based therapy for adults and adolescents.",
    servicesOffered: ["Psychological Testing", "ADHD Evaluation", "CBT", "Adolescent Therapy"],
    insuranceAccepted: ["Private Insurance", "Medicaid"],
    hoursOfOperation: "Mon–Thu 9am–6pm",
    contactFormEnabled: true,
    contactEmail: "intake@riverstonepsych.example.com",
    verified: true,
    featured: false,
    claimed: true,
    isPremium: true,
    imageUrl: IMG.office,
    galleryUrls: [IMG.office],
  },
  {
    slug: "harborview-psychiatric-group",
    name: "Harborview Psychiatric Group",
    category: "Psychiatrists",
    categorySlug: "psychiatrists",
    state: "New York",
    stateSlug: "new-york",
    address: "560 Presidio View St",
    zip: "10029",
    phone: "(212) 555-0187",
    website: "https://example.com",
    description:
      "Board-certified psychiatrists offering medication management and psychiatric evaluation for mood, anxiety, and thought disorders, in-person and via telehealth.",
    servicesOffered: ["Medication Management", "Psychiatric Evaluation", "Telepsychiatry"],
    insuranceAccepted: ["Private Insurance", "Medicare", "Medicaid"],
    hoursOfOperation: "Mon–Fri 8am–5pm",
    contactFormEnabled: true,
    contactEmail: "contact@harborviewpsych.example.com",
    socialLinks: { linkedin: "https://linkedin.com" },
    verified: true,
    featured: true,
    claimed: true,
    isPremium: true,
    imageUrl: IMG.clinic,
  },
  {
    slug: "golden-gate-mental-wellness",
    name: "Golden Gate Mental Wellness Clinic",
    category: "Mental Health Clinics",
    categorySlug: "mental-health-clinics",
    state: "California",
    stateSlug: "california",
    address: "902 Willow Creek Rd",
    zip: "94129",
    phone: "(415) 555-0176",
    website: "https://example.com",
    description:
      "Outpatient mental health clinic offering individual therapy, psychiatric care, and group programs for anxiety, depression, and trauma under one roof.",
    servicesOffered: ["Individual Therapy", "Group Programs", "Psychiatric Care", "Crisis Support"],
    insuranceAccepted: ["Private Insurance", "Medicaid", "Medicare"],
    hoursOfOperation: "Mon–Fri 7am–7pm",
    contactFormEnabled: true,
    contactEmail: "hello@ggmentalwellness.example.com",
    verified: true,
    featured: true,
    claimed: true,
    isPremium: true,
    imageUrl: IMG.clinic,
  },
  {
    slug: "clearwater-recovery-center",
    name: "Clearwater Recovery Center",
    category: "Substance Use Treatment Centers",
    categorySlug: "substance-use-treatment-centers",
    state: "Florida",
    stateSlug: "florida",
    address: "77 Fieldstone Dr",
    zip: "33755",
    phone: "(727) 555-0133",
    description:
      "A flexible outpatient and residential program offering individualized treatment plans for substance use and co-occurring mental health conditions.",
    servicesOffered: ["Residential Treatment", "Outpatient Program", "Dual Diagnosis Care"],
    insuranceAccepted: ["Medicaid", "Private Insurance"],
    contactFormEnabled: false,
    verified: false,
    featured: false,
    claimed: false,
    isPremium: false,
    imageUrl: IMG.office,
  },
  {
    slug: "riverbend-detox-clinic",
    name: "Riverbend Detox Clinic",
    category: "Detox Centers",
    categorySlug: "detox-centers",
    state: "Ohio",
    stateSlug: "ohio",
    address: "56 Mill Run Ct",
    zip: "43215",
    phone: "(614) 555-0154",
    website: "https://example.com",
    description:
      "24/7 medically monitored detox with direct transition support into residential or outpatient programs.",
    servicesOffered: ["Medical Detox", "24/7 Monitoring", "Transition Planning"],
    insuranceAccepted: ["Medicaid", "Medicare", "Private Insurance"],
    hoursOfOperation: "Open 24/7",
    contactFormEnabled: true,
    verified: true,
    featured: false,
    claimed: true,
    isPremium: false,
    imageUrl: IMG.clinic,
  },
  {
    slug: "sunridge-sober-living",
    name: "Sunridge Sober Living",
    category: "Sober Living Homes",
    categorySlug: "sober-living-homes",
    state: "Arizona",
    stateSlug: "arizona",
    address: "3300 Desert Bloom Way",
    zip: "85251",
    phone: "(480) 555-0111",
    website: "https://example.com",
    description:
      "A structured, gender-specific sober living home with peer accountability, house meetings, and coordination with local outpatient providers.",
    servicesOffered: ["Structured Housing", "Peer Support Meetings", "Curfew & Accountability", "Outpatient Coordination"],
    insuranceAccepted: ["Self-Pay"],
    hoursOfOperation: "Office hours Mon–Fri 9am–5pm",
    contactFormEnabled: true,
    contactEmail: "admissions@sunridgesober.example.com",
    socialLinks: { instagram: "https://instagram.com" },
    verified: true,
    featured: true,
    claimed: true,
    isPremium: true,
    imageUrl: IMG.home,
  },
  {
    slug: "brightpath-iop-services",
    name: "Brightpath IOP Services",
    category: "Intensive Outpatient Programs (IOP)",
    categorySlug: "intensive-outpatient-programs",
    state: "Illinois",
    stateSlug: "illinois",
    address: "214 Orchard Grove Ln",
    zip: "60614",
    phone: "(312) 555-0122",
    description:
      "Evening intensive outpatient programming for substance use and mental health, designed for clients balancing work, school, or family commitments.",
    servicesOffered: ["Evening IOP Sessions", "Family Therapy", "Relapse Prevention Planning"],
    insuranceAccepted: ["Medicaid", "Sliding Scale"],
    contactFormEnabled: false,
    verified: false,
    featured: false,
    claimed: false,
    isPremium: false,
    imageUrl: IMG.office,
  },
  {
    slug: "meridian-php-center",
    name: "Meridian Partial Hospitalization Center",
    category: "Partial Hospitalization Programs (PHP)",
    categorySlug: "partial-hospitalization-programs",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    address: "88 Beacon Hollow Rd",
    zip: "02116",
    phone: "(617) 555-0165",
    website: "https://example.com",
    description:
      "A structured day-treatment program bridging inpatient and outpatient care for individuals stepping down from a psychiatric hospitalization or crisis stay.",
    servicesOffered: ["Day Treatment", "Psychiatric Step-Down Care", "Group & Individual Sessions"],
    insuranceAccepted: ["Private Insurance", "Medicare"],
    hoursOfOperation: "Mon–Fri 8am–3pm",
    contactFormEnabled: true,
    contactEmail: "intake@meridianphp.example.com",
    verified: true,
    featured: false,
    claimed: true,
    isPremium: true,
    imageUrl: IMG.clinic,
  },
  {
    slug: "riverpark-residential-treatment",
    name: "Riverpark Residential Treatment Center",
    category: "Residential Treatment Centers",
    categorySlug: "residential-treatment-centers",
    state: "Colorado",
    stateSlug: "colorado",
    address: "902 Willow Creek Rd",
    zip: "80202",
    phone: "(303) 555-0176",
    website: "https://example.com",
    description:
      "Specializes in adolescent and adult residential treatment, combining clinical care with family therapy and structured daily programming.",
    servicesOffered: ["24/7 Residential Care", "Family Therapy", "Academic Support", "Individualized Treatment Plans"],
    insuranceAccepted: ["Private Insurance", "Self-Pay"],
    contactFormEnabled: true,
    contactEmail: "admissions@riverparktreatment.example.com",
    verified: true,
    featured: true,
    claimed: true,
    isPremium: true,
    imageUrl: IMG.home,
  },
  {
    slug: "willow-creek-assisted-living",
    name: "Willow Creek Assisted Living",
    category: "Assisted Living Facilities",
    categorySlug: "assisted-living-facilities",
    state: "North Carolina",
    stateSlug: "north-carolina",
    address: "410 Magnolia Court",
    zip: "27601",
    phone: "(919) 555-0140",
    website: "https://example.com",
    description:
      "A warm, community-centered assisted living residence offering personal care support, daily activities, and restaurant-style dining.",
    servicesOffered: ["Personal Care Assistance", "Medication Management", "Daily Activities", "Restaurant-Style Dining"],
    insuranceAccepted: ["Private Insurance", "Long-Term Care Insurance", "Self-Pay"],
    hoursOfOperation: "Tours by appointment, 7 days a week",
    contactFormEnabled: true,
    contactEmail: "tours@willowcreekliving.example.com",
    socialLinks: { facebook: "https://facebook.com" },
    verified: true,
    featured: true,
    claimed: true,
    isPremium: true,
    imageUrl: IMG.senior,
    galleryUrls: [IMG.senior, IMG.garden],
  },
  {
    slug: "harborlight-memory-care",
    name: "Harborlight Memory Care Community",
    category: "Memory Care Communities",
    categorySlug: "memory-care-communities",
    state: "Washington",
    stateSlug: "washington",
    address: "77 Fieldstone Dr",
    zip: "98101",
    phone: "(206) 555-0133",
    description:
      "A secure, purpose-built memory care community for individuals with Alzheimer's and other forms of dementia, with a dedicated specialized-care staff ratio.",
    servicesOffered: ["Secure Memory Care Neighborhood", "Specialized Dementia Programming", "24/7 Nursing Support"],
    insuranceAccepted: ["Long-Term Care Insurance", "Self-Pay"],
    contactFormEnabled: false,
    verified: false,
    featured: false,
    claimed: false,
    isPremium: false,
    imageUrl: IMG.senior,
  },
  {
    slug: "cedar-grove-independent-living",
    name: "Cedar Grove Independent Living",
    category: "Independent Senior Living",
    categorySlug: "independent-senior-living",
    state: "Oregon",
    stateSlug: "oregon",
    address: "3300 Desert Bloom Way",
    zip: "97201",
    phone: "(503) 555-0111",
    website: "https://example.com",
    description:
      "An active-adult independent living community with private apartments, on-site fitness and wellness programs, and a full activities calendar.",
    servicesOffered: ["Private Apartments", "Fitness & Wellness Center", "Social & Activities Calendar", "Housekeeping"],
    insuranceAccepted: ["Self-Pay"],
    hoursOfOperation: "Leasing office Mon–Sat 9am–5pm",
    contactFormEnabled: true,
    contactEmail: "leasing@cedargroveliving.example.com",
    verified: true,
    featured: false,
    claimed: true,
    isPremium: true,
    imageUrl: IMG.senior,
  },
  {
    slug: "pinehaven-skilled-nursing",
    name: "Pinehaven Skilled Nursing Facility",
    category: "Skilled Nursing Facilities",
    categorySlug: "skilled-nursing-facilities",
    state: "Michigan",
    stateSlug: "michigan",
    address: "214 Orchard Grove Ln",
    zip: "48226",
    phone: "(313) 555-0122",
    website: "https://example.com",
    description:
      "24-hour skilled nursing care with on-site physical, occupational, and speech therapy for short-term rehabilitation and long-term residents.",
    servicesOffered: ["24-Hour Skilled Nursing", "Physical Therapy", "Occupational Therapy", "Short-Term Rehab"],
    insuranceAccepted: ["Medicare", "Medicaid", "Private Insurance"],
    contactFormEnabled: true,
    contactEmail: "admissions@pinehavensnf.example.com",
    verified: true,
    featured: true,
    claimed: true,
    isPremium: true,
    imageUrl: IMG.nurse,
  },
  {
    slug: "gentle-path-hospice",
    name: "Gentle Path Hospice",
    category: "Hospice Providers",
    categorySlug: "hospice-providers",
    state: "Tennessee",
    stateSlug: "tennessee",
    address: "560 Presidio View St",
    zip: "37203",
    phone: "(615) 555-0187",
    description:
      "Compassionate end-of-life hospice care delivered at home, in facilities, or in our inpatient unit, with 24/7 nurse support for patients and families.",
    servicesOffered: ["In-Home Hospice Care", "Inpatient Hospice Unit", "24/7 Nurse Support", "Grief & Bereavement Counseling"],
    insuranceAccepted: ["Medicare", "Medicaid", "Private Insurance"],
    contactFormEnabled: false,
    verified: false,
    featured: false,
    claimed: false,
    isPremium: false,
    imageUrl: IMG.hands,
  },
  {
    slug: "trueheart-home-health",
    name: "TrueHeart Home Health Agency",
    category: "Home Health Agencies",
    categorySlug: "home-health-agencies",
    state: "Georgia",
    stateSlug: "georgia",
    address: "902 Willow Creek Rd",
    zip: "30303",
    phone: "(404) 555-0176",
    website: "https://example.com",
    description:
      "Licensed home health agency providing skilled nursing, physical therapy, and personal care visits for patients recovering or aging in place at home.",
    servicesOffered: ["Skilled Nursing Visits", "Physical Therapy at Home", "Personal Care Aides", "Medication Reminders"],
    insuranceAccepted: ["Medicare", "Medicaid", "Private Insurance"],
    hoursOfOperation: "On-call 24/7, office Mon–Fri 8am–6pm",
    contactFormEnabled: true,
    contactEmail: "referrals@truehearthh.example.com",
    socialLinks: { facebook: "https://facebook.com", linkedin: "https://linkedin.com" },
    verified: true,
    featured: true,
    claimed: true,
    isPremium: true,
    imageUrl: IMG.nurse,
  },
  {
    slug: "compass-case-management-services",
    name: "Compass Case Management Services",
    category: "Case Management Services",
    categorySlug: "case-management-services",
    state: "Pennsylvania",
    stateSlug: "pennsylvania",
    address: "118 Bay Vista Ave",
    zip: "19102",
    phone: "(215) 555-0198",
    description:
      "Independent case managers who coordinate care plans, benefits navigation, and provider referrals for individuals managing complex medical or behavioral health needs.",
    servicesOffered: ["Care Plan Coordination", "Benefits Navigation", "Provider Referrals", "Family Consultation"],
    insuranceAccepted: ["Private Insurance", "Self-Pay"],
    contactFormEnabled: false,
    verified: false,
    featured: false,
    claimed: false,
    isPremium: false,
    imageUrl: IMG.office,
  },
];

export const stateSummaries: StateSummary[] = Array.from(
  providers.reduce((map, p) => {
    map.set(p.stateSlug, {
      name: p.state,
      slug: p.stateSlug,
      providerCount: (map.get(p.stateSlug)?.providerCount ?? 0) + 1,
    });
    return map;
  }, new Map<string, StateSummary>())
).map(([, v]) => v);

export const categorySummaries: CategorySummary[] = CATEGORIES.map((c) => ({
  name: c.name,
  slug: c.slug,
  providerCount: providers.filter((p) => p.categorySlug === c.slug).length,
}));

export function getProvider(stateSlug: string, categorySlug: string, slug: string) {
  return providers.find(
    (p) => p.stateSlug === stateSlug && p.categorySlug === categorySlug && p.slug === slug
  );
}

export function getProviderBySlug(slug: string) {
  return providers.find((p) => p.slug === slug);
}

export function getFeatured() {
  return providers.filter((p) => p.featured);
}
